<?php
/**
 * davidbel/magento-ai-search by David Belicza
 * SPDX-License-Identifier: MIT
 * https://github.com/DavidBelicza/Magento-AI-Search
 */
declare(strict_types=1);

/** @var \Magento\Backend\Block\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="ai-search-dashboard">
    <?= /* @noEscape */ $block->getChildHtml('progress') ?>
    <h2 class="ai-search-dashboard-title"><?= $escaper->escapeHtml(__('Testing')) ?></h2>
    <div class="ai-search-dashboard-action">
        <?= /* @noEscape */ $block->getChildHtml('test_embedder_connection') ?>
    </div>
    <div class="ai-search-dashboard-action">
        <?= /* @noEscape */ $block->getChildHtml('test_semantic_search') ?>
    </div>
</div>
